### ISSUE TITLE
function Base.isvalid must be explicitly imported to be extended

### ISSUE THREAD

**Issue by pkofod** [MichaelHatherly/Docile.jl#146]
I see there have been similar issues before. I would love to fix the problem, but I'm not exactly sure what to do to make 

```ERROR: LoadError: LoadError: LoadError: error in method definition: function Base.isvalid must be explicitly imported to be extended```

go away on Version 0.4.0-dev+5933 (2015-07-12 17:39 UTC) .

**Comment by MichaelHatherly** [comment]
@pkofod I think this was fixed in 8d02670282965ee91a0e1d5a5ab9ffe18ff9fcfd, more specifically this line https://github.com/MichaelHatherly/Docile.jl/commit/8d02670282965ee91a0e1d5a5ab9ffe18ff9fcfd#diff-39bff96f412f0d5809c8902e8a9010feR28. It should be fixed in the latest release of Docile, which version are you currently using?

**Comment by pkofod** [comment]
Apparently I had a dirty copy (wonder what I've changed), so it didn't update it properly! Thanks, it works now.

**Comment by MichaelHatherly** [comment]
> Apparently I had a dirty copy (wonder what I've changed)

A while back I mistakenly commited files what were only different in case, so if you're on a case insensitive OS then git ends up marking the repo as dirty. That could have been it. Glad it's working now.

**Comment by pkofod** [comment]
I'm on ubuntu, so that would indeed be case sensitive. As long as it is working now :)
