### ISSUE TITLE
New line using docile?

### ISSUE THREAD

**Issue by nassarhuda** [MichaelHatherly/Docile.jl#155]
I am trying to get a new line in my documentation without adding an empty line in between.

'\n' works but it adds an extra empty line in between the two lines - I don't want that
I tried 2 spaces followed by the return key (treating the documentation as markdown) -> puts the two lines on the same line

Example - note that scomponents(A).number is followed by 2 spaces:
```
cc = scomponents(A)\n
scomponents(A).number  
scomponents(A).sizes
```
From julia, output looks like the following:
```
help?> scomponents
  cc = scomponents(A)

  scomponents(A).number    scomponents(A).sizes
```

**Comment by MichaelHatherly** [comment]
The markdown parser is targeting the CommonMark spec so I assume that this feature would be http://spec.commonmark.org/0.22/#hard-line-breaks.

From what I can tell it's not been implemented in `Base.Markdown` just yet and from a quick search of the main Julia issues list it's not been brought up either.

Could you open an issue for this at https://github.com/JuliaLang/julia/issues rather since the parser is part of base Julia from 0.4 onwards.

That said, if you are just wanting verbatim text such as for code examples, https://github.com/nassarhuda/MatrixNetworks.jl/commit/2dc0a1c2975aca23030bc22de9e15835a03b267b#diff-74356ff377b83988beae83bda7dd16ecL43, then you can just use a [fenced code](http://spec.commonmark.org/0.22/#fenced-code-blocks) block delineated by backticks or [indented with 4 spaces](http://spec.commonmark.org/0.22/#indented-code-blocks).
