### ISSUE TITLE
rewrite: docstring containing "***"

### ISSUE THREAD

**Issue by thofma** [MichaelHatherly/Docile.jl#163]
I have lots of docstrings containing "\*\*\*", which is a markdown syntax for a horizontal rule. When doing makedocs(), the string "\*\*\*" in a docstring gets converted into "–––" in the corresponding \*.md file. This is unfortunately not a horizontal rule.

On the other hand, `md"***"` produces the correct result, so it is not a markdown parser problem I guess.

**Comment by MichaelHatherly** [comment]
As far as I can see this seems to be a rendering issue with `Base.Markdown` rather than with Docile, see [this](https://github.com/JuliaLang/julia/blob/f0e2ec155c939f65db6066faf2ca1ee4aa1b89a3/base/markdown/render/plain.jl#L49-L51) method. The `–` should be a `-`. If you redefine the method at the REPL with:

```julia
julia> function Markdown.plain(io::IO, ::Markdown.HorizontalRule)
           println(io, "-"^3)
       end
```

then is should output the correct `-` char. If that fixes the problem could you submit the fix to the julia repo?

**Comment by thofma** [comment]
That fixes it. Thank you for the quick reply. I will submit a fix to the julia repo.

**Comment by thofma** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/14464
