### ISSUE TITLE
Type aliases

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Docile.jl#57]
Not sure if this is better here or with Lexicon.

Type aliases are problematic. Because they seem to get aliased so quickly, the identification of these is lost. It's not a problem at the REPL if you type `?MyAlias`. But, it is a problem with HTML saved by Lexicon. There's no entry of aliases in the contents or headings. Is it possibly to grab aliases during `@doc` parsing?

As a work-around, I put a large `**MyAlias**` at the top of such entries.

**Comment by MichaelHatherly** [comment]
Yes, this is more related to Docile. Since Docile tries to store the actual object references as the keys in [`Metadata`](https://github.com/MichaelHatherly/Docile.jl/blob/778290ca466572cf351bbe826eb9356e138cfe50/src/Docile.jl#L20), this means that they just end up as references to the aliased type.

The current exception to this is globals, which are stored as symbols to avoid just storing a meaningless value in the `ObjectIdDict`. It might be possible to do the same thing with aliases as well and just store `:MyAlias` rather.

**Comment by MichaelHatherly** [comment]
Closed by 09cc1cca80f73d178aad8bdd8566815f014421fa. `typealias` is now stored in the same manner as globals, ie as a `Symbol` in the modules `__METADATA__.entries`. Surprisingly, this requires no changes to the Lexicon side of things.
