### ISSUE TITLE
Use method dispatch to group methods

### ISSUE THREAD

**Issue by tshort** [MichaelHatherly/Docile.jl#60]
This aims to help with the problem of grouping methods (#38 and https://github.com/MichaelHatherly/Lexicon.jl/issues/14).

Method dispatch can allow easier look-up in the REPL for grouped method entries. Here's what it could look like to document indexing on DataFrames::

```julia
@docm getindex(df::AbstractDataFrame, args...) = """
    docstring ...
"""
```
From the user point of view, `?mydf[2:30, :colA]` and `?mydf[:colA]` would both return the same docstring.

That `@docm` macro would translate roughly to code as follows:

```julia
entry = Entry(docstring)
querymethods(Key{:getindex}, ::AbstractDataFrame, args...) = entry
method =   # some code to find the method just created
metadata.entries[method] = entry
```
Then, `query` would use `querymethods` to look up entries.

Advantages of this approach include:

* Flexible way to get `?fun(x, y, z)` to work for several groups of methods.

* The documented method comes before the docstring. With longish standard `@doc` strings, it's sometimes not obvious what's being documented unless there are comments in the code.

* The method definition itself conveys information about what the docstring covers.

**Comment by MichaelHatherly** [comment]
We could probably get away with syntax such as:

```julia
"""
docstring ...
"""
(getindex, AbstractDataFrame, Any...) # or `:getindex` if it's not yet defined.
```

It would probably just need some additions to `builddocs.jl` such as in [`isdocumentable`](https://github.com/MichaelHatherly/Docile.jl/blob/e5c9e4e250332c768e9607a689efe8632c139e8d/src/builddocs.jl#L161) so that Docile knows tuples are able to be documented. Then creating a single `Entry` object containing the docstring and adding it to all the methods resulting from `methods(getindex, (AbstractDataFrame, Any...))`.

This is kind of how `Vararg` functions get documented already. See [this](https://github.com/MichaelHatherly/Docile.jl/blob/e5c9e4e250332c768e9607a689efe8632c139e8d/src/method-lookup.jl#L151-L177) part of the method lookup code. A function such as `Docile.meta(docs = "")` is documented in this way.

REPL output:

```
Docile.meta()
Docile.meta(doc)

  Add additional metadata to a documented object.
...
```
All the methods that are associated with a particular `Entry` get displayed as a single docstring in the REPL output.

Although using dispatch, `querymethods` here, to do all this is rather attractive I fear we might run into similar problems to [this one](https://github.com/MichaelHatherly/Docile.jl/issues/51) by trying to determine which methods are applicable if they're being imported from another module. There may be a workaround, but I've not managed to find one as of yet.

Also, keeping all the docstring loading/parsing "lazy" (avoiding the macros basically) as in the new code in master improves package load times quite a bit I've found.

For long docstrings I'm a fan of using either `meta(file = "docs.md")` or the new `file"docs.md"` macro, but that's really just personal preference I guess.

**Comment by tshort** [comment]
Although it's not quite as attractive looking, your suggestion would definitely fit my needs. It should give the same user experience and grouping capability. 

I haven't been able to figure out your code well enough to be able to give your suggestion a try.

**Comment by MichaelHatherly** [comment]
True, not quite as nice looking, but much easier to add than I suspected. It's done in 6a7d5513f229c3068d778886577b2b15579c70a7.

**Comment by tshort** [comment]
Wow, you got that done fast:)
