### ISSUE TITLE
Documenting function parameters with new system

### ISSUE THREAD

**Issue by Ward9250** [MichaelHatherly/Docile.jl#66]
Hi,

I'm updating the code for documenting one of my Julia packages I worked on with someone else, they first wrote up the documentation, since Docile.jl has now changed I'm going through and updating it. I have a question:

metadata can be added to documentation of a method or function using the meta() function: I have some code that looks like this:

```julia
@doc """
PhyExtension allows defining arbitrary metadata to annotate nodes.

This allows the PhyNode type to support any phylogenetic tree format that includes annotations (e.g. PhyloXML, NeXML), and allows programmatic extension of nodes with annotations.
""" {
 :section => "PhyExtension"
} ->
type PhyExtension{T}
  value::T
end
```

Which I've now changed to:

```julia
@doc meta("""
PhyExtension allows defining arbitrary metadata to annotate nodes.
This allows the PhyNode type to support any phylogenetic tree format that includes annotations (e.g. PhyloXML, NeXML), and allows programmatic extension of nodes with annotations.
"""; section => "PhyExtension") ->
type PhyExtension{T}
value::T
end
```

First, is this the correct way to do this? I know "section" was an important word as it put documentation in the right place.

Second I have some documentation written under the old system like this:
```julia
@doc """
Create a PhyNode.

PhyNodes represent nodes in a phylogenetic tree. All arguments are optional when creating PhyNodes:

\`\`\`julia
one = PhyNode()
two = PhyNode(name = "two",
              branchlength = 1.0,
              parent = one)
\`\`\`

""" {
  :section => "PhyNode",
  :parameters => {
    (:name,
     "The name of the node (optional). Defaults to an empty string, indicating the node has no name."),
    (:branchlength,
     "The branch length of the node from its parent (optional). Defaults to `-1.0`, indicating an unknown branch length."),
    (:ext,
     "An array of zero or more PhyExtensions (optional). Defaults to an empty array, i.e. `[]`, indicating there are no extensions."),
    (:parent,
     "The parent node (optional). Defaults to a self-reference, indicating the node has no parent.")},
  :returns => (PhyNode)
} ->
[... Function code here ...]
```
I was wondering how I go about updating this to the new Docile system - the :parameters part containing many symbol - string pairs is throwing me, do I simply change it to the new dictionary syntax?

Thanks,
Ben.

**Comment by MichaelHatherly** [comment]
Hi Ben,

The current state of `meta` has probably been best described in [this](https://github.com/MichaelHatherly/Lexicon.jl/issues/6#issuecomment-71398525) thread (starting from the linked comment).

In summary: my current feeling is that we should be getting the docs system to *extract* the metadata for us rather than having to do this manually using `meta` and it's associated syntax. I thought `meta` was a great idea initially, but I've found it gets quite tedious writing out long `:parameters` lists!

The best suggestion I can give is to format any metadata you wish to store directly in the docstring using markdown syntax (or really any way that looks good) so that it's *human*-readable. Hopefully the community will settle on some best practices eventually that can then be used to extract metadata automatically for us.

For the example you've listed the new syntax should be:

```julia
@doc meta("""
Create a PhyNode.

PhyNodes represent nodes in a phylogenetic tree. All arguments are optional when creating PhyNodes:

\`\`\`julia
one = PhyNode()
two = PhyNode(name = "two",
              branchlength = 1.0,
              parent = one)
\`\`\`

""", section = "PhyNode",
      parameters = {
    (:name,
     "The name of the node (optional). Defaults to an empty string, indicating the node has no name."),
    (:branchlength,
     "The branch length of the node from its parent (optional). Defaults to `-1.0`, indicating an unknown branch length."),
    (:ext,
     "An array of zero or more PhyExtensions (optional). Defaults to an empty array, i.e. `[]`, indicating there are no extensions."),
    (:parent,
     "The parent node (optional). Defaults to a self-reference, indicating the node has no parent.")},
  returns = (PhyNode,)
} ->
[... Function code here ...]
```

If you were to add the metadata to the docstring itself then perhaps something like:

```julia
@doc """

    func_name(args...) -> (PhyNode,)

Create a PhyNode.

PhyNodes represent nodes in a phylogenetic tree. All arguments are optional
when creating PhyNodes.

**Example:**

    one = PhyNode()
    two = PhyNode(name = "two",
                  branchlength = 1.0,
                  parent = one)

**Parameters:**

* `name`:         The name of the node (optional). Defaults to an empty string, indicating
                  the node has no name.

* `branchlength`: The branch length of the node from its parent (optional).
                  Defaults to `-1.0`, indicating an unknown branch length.

* `ext`:          An array of zero or more PhyExtensions (optional). Defaults to an empty
                  array, i.e. `[]`, indicating there are no extensions.

* `parent`:       The parent node (optional). Defaults to a self-reference, indicating
                  the node has no parent.
""" ->
[... Function code here ...]
```

This is the way I've been writing docstrings for a while now, I've found it to be much more readable.

Regarding the `:section`, the actual logic needed in Lexicon.jl to take advantage of sections was never actually added. What might work instead is the recent filtering and sorting api that @tsort implemented. See https://github.com/MichaelHatherly/Lexicon.jl/pull/27. AFAIK Tom's package https://github.com/tshort/Sims.jl makes use of this to customize the static docs. There's probably even more we could do to make exporting docs better; ideas are most welcome.
