### ISSUE TITLE
clarify relationship with 0.4

### ISSUE THREAD

**Issue by hayd** [MichaelHatherly/Docile.jl#68]
I'm confused by the difference between Docile and base / what the lay of the land is.

The docs say the difference is with the `@doc*` macro (which sounds like it may be useful to have in base (potentially changes should be merged to base? similar to what we were previously discussing to covert rst docs to md cc @one-more-minute).... there's also meta (but I don't think that's mentioned in the docs). Are base's methods being overwritten?

This is discussed a bit here: https://groups.google.com/forum/#!topic/julia-users/wBZGlzFo7eI, and I've asked before.... but I'm still a confused. :(

**Comment by MichaelHatherly** [comment]
The (hopefully) eventual syntax for docstrings is mentioned in https://github.com/JuliaLang/julia/issues/8965 &ndash; the macro syntax should just be a stepping stone towards that I believe.

This syntax won't play nicely with `@doc*` or `meta` usage as far as I can see, which has been my reason for not pushing very hard to get them added to base.

`@doc` gets overwritten if imported in 0.4, but that's solvable by conditionally importing Docile in a package. I've not come across any other places where methods have been overwritten.

**Comment by hayd** [comment]
Thanks. Does this mean in 0.4 you can get away with only defining `meta` and `@doc*` (and using the base version of everything else)?

I still think there could be a case for including these in base, esp. `@doc*` - many base function attach to a main docstring (and from the rsts that's really the only choice)...

An alternative I was thinking about grouping methods by docstring, as several methods may **share** the same docstring - or parts of (but the docstring is not shared across all methods). e.g. things with optional arguments (in the rsts):

    f(a, [b, [c]])              # these 3 methods share a docstring
    f(somethingelse::Foo, [b])  # these 2 methods share a docstring

**Comment by MichaelHatherly** [comment]
> Does this mean in 0.4 you can get away with only defining meta and `@doc*` (and using the base version of everything else)?

By this do you mean using `Base.Docs.@doc` with `Docile.meta` and `Docile.@doc*`? Note that `@doc*` is just `@doc` with an additional argument, `:*`. Also, even if this did work, you'd have docstrings stored in different places &ndash; `__METADATA__` and `META` &ndash; which probably wouldn't be a great idea.

> I still think there could be a case for including these in base, esp. `@doc*` - many base function attach to a main docstring (and from the rsts that's really the only choice)...

The features of `meta` and `@doc*` are useful, definitely. For adding docs to a `Function` in 0.4 you can just do

```julia
f(x) = x

@doc " ... " ->
f
```

though. `meta` and `@doc*` don't fit well with plain docstrings though since (using hypothetical builtin syntax) allowing

```julia
meta(" ... ", foo = :bar)
foobar(x) = x
```

raises the question of what exactly counts as documentation if it's placed before something? Do we special-case `meta`? And for `@doc*` equivalence:

```julia
" ... "
function foobar end
```

or something like that would be needed.

> An alternative I was thinking about grouping methods by docstring, as several methods may share the same docstring - or parts of (but the docstring is not shared across all methods).

Docile's plain string syntax already allows something similar to this:

```julia
" ... "
[foobar, foobar!]
```

Optional arguments in methods are also supported with slightly more verbose syntax. Opinions/suggestions on the approach taken there would be much appreciated.

**Comment by hayd** [comment]
> Also, even if this did work, you'd have docstrings stored in different places – __METADATA__ and META – which probably wouldn't be a great idea.

so atm `Docile.@doc` looks up help in a different help dict than Base.@doc??

**Comment by MichaelHatherly** [comment]
Yes. In [`Base`](https://github.com/JuliaLang/julia/blob/b0468601820698d6fa8ab1b59d5f1490f6220dd4/base/docs.jl#L14) and [`Docile`](https://github.com/MichaelHatherly/Docile.jl/blob/34ca314a33253f4ee19e7cb88799dbd68cae8efc/src/Docile.jl#L12). `__METADATA__` and `META` shouldn't be accessed directly, rather via the available getters/setters so I'm not sure it's much of an issue. Have you run into problems with the differing names?

That said, once 0.4 begins to settle down I'll look into bringing things up to date where necessary.

**Comment by hayd** [comment]
I've certainly had issues where import Docile breaks help. I'm not sure if this is simply due to overwriting `@doc` but maintaining two metadata dicts with more or less the same thing feels like a recipe for weird errors (as well as some unnecessary duplication).

It would be great if there was a canonical way/API to write to Base.META so that `Base.@doc` (help) stilll works *and* reads it as Docile intends it... perhaps this can be done by writing some writemime methods or something (confession: I haven't delved into the Docile code :s ) - as in the Ref example in Markdown.

cc @one-more-minute

**Comment by one-more-minute** [comment]
> It would be great if there was a canonical way/API to write to Base.META so that `Base.@doc` (help) stilll works and reads it as Docile intends it...

`doc(X, Y)` just associates object X with meta Y, and `doc(X)` then retrieves Y. That really is the whole doc system. All of the `@doc` macro stuff is just sugar built on top, and anything else you want to build on top via Docile should be doable too – I don't think it's possible to be more general than that.

**Comment by hayd** [comment]
@one-more-minute Are you saying that Docile should be doing that in 0.4 rather than have it's own METADATA dict?

---

> Optional arguments in methods are also supported with slightly more verbose syntax. 

Ah great, I didn't know about that at all, will have another look in the docs and get back to you!

It seems that `@doc` to a specific signature on a method or `@doc*` to global are diametrically opposite ideas. I would definitely prefer to see the former used exclusively as it seems more julian (and shared docstrings over signatures is clearly something we'll see in real-word documentation as well as base). Not having docstring sharing as syntax at definition time, but requiring a macro or method, seems perfectly reasonable.

It seems like you want the help/`@doc` globally on a function with multiple methods that share docstrings (as above) to not show repetitions.
```
help?> f
the signature of three methods (either as a union or with the optional syntax)
docstring for these three methods

the signature of two methods
docstring for the two methods
```
rather than repeating the docstring 5 times (one for each signature)... Obviously you can make this work with `@doc*` but it feels inelegant/not julian (and you lose the ability of specific help on a signature).

Am I making any sense?? (I feel the need to dig around and have a play here.)

**Comment by MichaelHatherly** [comment]
> `doc(X, Y)` just associates object `X` with meta `Y`, and `doc(X)` then retrieves `Y`.

Docile's are just named differently at this point; that can be changed relatively easily. I'm also storing a few extra fields in `__METADATA__` such as `include`d files, but doesn't really affect docstring getter/setter methods.

> Ah great, I didn't know about that at all, will have another look in the docs and get back to you!

FYI it's specific to plain docstrings, not `@doc`-style ones. I'm sure there's cases that aren't handled correctly at the moment / could be more user-friendly.

> It seems that `@doc` to a specific signature on a method or `@doc*` to global are diametrically opposite ideas.

`@doc*` is *only* shorthand for the specific case of documenting the `Function` rather than `Method` it is applied to:

```julia
@doc* " ... " ->
f(x) = x
```

is the same as

```julia
f(x) = x
@doc " ... " -> f
```

it has no other uses currently.

> It seems like you want the help/`@doc` globally on a function with multiple methods that share docstrings (as above) to not show repetitions.

Currently for shared docstrings Lexicon will display something like:

```
help?> f
f (generic function with 5 methods)
  1: Sandbox.f(somethingelse::Foo)
  2: Sandbox.f(somethingelse::Foo, b)
  3: Sandbox.f(a::Bar, b, c)
  4: Sandbox.f(a::Bar, b)
  5: Sandbox.f(a::Bar)
```

where the docs for method one can then be selected via:

```
help?> f 1

... docs for f(::Foo) displayed ...
```

If all signatures matching a query have the same docstring then it will be displayed once with the matching signatures concatenated above. If there's more than one applicable docstring for a query then the menu seen above would be displayed without any actual docstrings. I've found this to be the nicest compromise between too much / little information.

**Comment by hayd** [comment]
I like that. How does that square if you have an additional methods defined with `@doc*` ?

I think that is a nice way to do it, and would be a better fix than https://github.com/JuliaLang/julia/pull/9838 (but in a less noisy way when you have a dozen or so methods), would **love** to see this improved in Base.

(When I say diametrically opposite I just mean that attaching to functions vs methods.)

**Comment by MichaelHatherly** [comment]
> How does that square if you have an additional methods defined with `@doc*`?

Sorry for the slow reply. Could you clarify which "that" you're referring to here?

If you have a

```julia
@doc* " ... " -> f
```

as well as the docstrings attached to `Method` objects then it would just list

```
help?> f
f (generic function with 5 methods)
  1: Sandbox.f
  2: Sandbox.f(somethingelse::Foo)
  3: Sandbox.f(somethingelse::Foo, b)
  4: Sandbox.f(a::Bar, b, c)
  5: Sandbox.f(a::Bar, b)
  6: Sandbox.f(a::Bar)
```

instead. (If that's what you were asking.)
