### ISSUE TITLE
docs: double entries

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Docile.jl#70]
just a small thing I noticed when reading the docs.

http://docilejl.readthedocs.org/en/latest/api/Docile/

under: **Exported**

There are 2 times the same docs for: `meta()` and `meta(doc)` which looks not best.

Does the `@doc+` not help to avoid such?

**Comment by MichaelHatherly** [comment]
Dup of https://github.com/MichaelHatherly/Lexicon.jl/issues/17

> Does the `@doc+` not help to avoid such?

For this particular case, yes. `meta` should probably just be a documented `Function` rather than `Method`, but `@doc+` won't help in general.

It's mostly just an issue of not showing duplicate `Entry` objects in the generated output (like the repl output already does). Aggregating all objects that share a common `Entry` and displaying the aggregation would probably look better.

Closing this in favour of the Lexicon issue linked above. (Should probably have a better title for that issue anyway.)
